[package]
name = "rustx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
config = "0.11.0"
gtk = "0.9.0"
gio = "0.9.0"
uuid = "1.0.0-alpha.1"
rand = "0.8"
des = "0.7"
block-modes = "0.8"
hex = "0.4"

[[bin]]
name = "message_broker_client"
path = "src/message_broker_client.rs"

[[bin]]
name = "message_broker_server"
path = "src/message_broker_server.rs"

[[bin]]
name = "sistema_monitoreo"
path = "src/apps/sistema_monitoreo.rs"

[[bin]]
name = "sistema_camaras"
path = "src/apps/sistema_camaras.rs"

[[bin]]
name = "generar_camaras"
path = "src/apps/generar_camaras.rs"