[package]
name = "rust-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"

[[bin]]
name = "message-broker-client"
path = "src/message-broker-client.rs"

[[bin]]
name = "message-broker-server"
path = "src/message-broker-server.rs"